name: Generate Image Prompt

on:
  workflow_dispatch:

jobs:
  prompt-creation:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Generate Image Prompt
        run: |
          python3 - <<EOF
          import os
          import requests
          import json

          STORY_FILE_PATH = "scriptgen/generated_story.txt"
          with open(STORY_FILE_PATH, "r", encoding="utf-8") as f:
              story_text = f.read()

          url = "https://openrouter.ai/api/v1/chat/completions"
          headers = {
              "Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}",
              "Content-Type": "application/json",
              "HTTP-Referer": "https://your-site.com",
              "X-Title": "Visual Prompt Gen"
          }

          prompt = (
              "You are a visual artist assistant. Read the story below and identify the most dramatic, cinematic, or emotionally intense scene. "
              "Then describe it as a single image generation prompt for an AI model. "
              "Include only important visual elements like character actions, setting, clothing, mood, time of day, lighting, and composition. "
              "Avoid extra words. Use a professional prompt style.\n\n"
              f"Story:\n{story_text}\n\n"
              "Provide only the prompt:"
          )

          data = {
              "model": "nvidia/llama-3.3-nemotron-super-49b-v1:free",
              "messages": [
                  {"role": "user", "content": prompt}
              ]
          }

          response = requests.post(url, headers=headers, data=json.dumps(data))
          if response.status_code == 200:
              prompt_text = response.json()['choices'][0]['message']['content'].strip()
              with open("scriptgen/image_prompt.txt", "w", encoding="utf-8") as out:
                  out.write(prompt_text)
              print("Image prompt saved.")
          else:
              print(f"Error {response.status_code}: {response.text}")
          EOF

      - name: Commit and Push Prompt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add scriptgen/image_prompt.txt
          git commit -m "Add generated image prompt"
          git push
