name: Run Story Generator

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  generate-story:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your preferred version

    - name: Install dependencies
      run: pip install requests

    - name: Run the story generator
      run: python story_generator.py
      working-directory: .  # Set to root; update if story_generator.py is in a subfolder
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
