name: Run Story Generator

on:
  workflow_dispatch:  # Allows manual trigger in GitHub Actions tab

jobs:
  generate-story:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the story generator
      run: |
        python story_generator.py
