name: Run Story Generator

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  generate-story:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run the story generator
        run: python story_generator.py
        working-directory: scriptgen  # Path where your script is located
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
